/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Windows;

import Treatment.*;
import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author alexa
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     */
    
    private static boolean JOUR = false;
    private static boolean NUIT = true;
    
    private boolean mode;
    private int jour;
    
    int nbVisiteurs;
    
    ThreadIntruder ti;
    ThreadDate td; 

    public void setMode(boolean mode) {
        this.mode = mode;
    }

    public void setJour(int jour) {
        this.jour = jour;
    }

    public int getJour() {
        return jour;
    }
    
    
    
    public MainWindow() {
        initComponents();
        
        setMode(JOUR);
        setJour(0);
        nbVisiteurs = 0;
        
        jlp_jour.setOpaque(true);
        jlp_jour.setVisible(true);
        
        jlp_nuit.setOpaque(false);
        jlp_nuit.setVisible(false);
        
        ti = new ThreadIntruder(false, this);
        td = new ThreadDate(true, this); 
        td.start();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlp_jour = new javax.swing.JLayeredPane();
        jb_mode_nuit = new javax.swing.JButton();
        jl_titre_jour = new javax.swing.JLabel();
        jl_intitule_visiteurs = new javax.swing.JLabel();
        jl_nb_visiteurs = new javax.swing.JLabel();
        jl_date = new javax.swing.JLabel();
        jb_plus = new javax.swing.JButton();
        jlp_nuit = new javax.swing.JLayeredPane();
        jb_mode_jour = new javax.swing.JButton();
        jl_ttitre_nuit = new javax.swing.JLabel();
        jl_led = new javax.swing.JLabel();
        jb_intru = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jb_mode_nuit.setText("Mode Nuit");
        jb_mode_nuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_mode_nuitActionPerformed(evt);
            }
        });

        jl_titre_jour.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        jl_titre_jour.setText("MODE JOUR :");

        jl_intitule_visiteurs.setFont(new java.awt.Font("Sylfaen", 0, 12)); // NOI18N
        jl_intitule_visiteurs.setText("Nombre de visiteurs aujourd'hui :");

        jl_nb_visiteurs.setFont(new java.awt.Font("Sylfaen", 0, 12)); // NOI18N
        jl_nb_visiteurs.setText("0");

        jl_date.setFont(new java.awt.Font("Sylfaen", 0, 12)); // NOI18N
        jl_date.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jb_plus.setText("+");
        jb_plus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_plusActionPerformed(evt);
            }
        });

        jlp_jour.setLayer(jb_mode_nuit, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlp_jour.setLayer(jl_titre_jour, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlp_jour.setLayer(jl_intitule_visiteurs, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlp_jour.setLayer(jl_nb_visiteurs, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlp_jour.setLayer(jl_date, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlp_jour.setLayer(jb_plus, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jlp_jourLayout = new javax.swing.GroupLayout(jlp_jour);
        jlp_jour.setLayout(jlp_jourLayout);
        jlp_jourLayout.setHorizontalGroup(
            jlp_jourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jlp_jourLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jb_mode_nuit)
                .addGap(130, 130, 130))
            .addGroup(jlp_jourLayout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addGroup(jlp_jourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jl_date, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_titre_jour))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jlp_jourLayout.createSequentialGroup()
                .addGroup(jlp_jourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jlp_jourLayout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(jl_intitule_visiteurs)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addComponent(jl_nb_visiteurs, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jlp_jourLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jb_plus, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        jlp_jourLayout.setVerticalGroup(
            jlp_jourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jlp_jourLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jl_titre_jour, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jl_date, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jlp_jourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_intitule_visiteurs)
                    .addComponent(jl_nb_visiteurs))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jb_plus)
                .addGap(70, 70, 70)
                .addComponent(jb_mode_nuit)
                .addGap(57, 57, 57))
        );

        jlp_nuit.setBackground(new java.awt.Color(0, 0, 153));
        jlp_nuit.setForeground(new java.awt.Color(0, 0, 153));
        jlp_nuit.setPreferredSize(new java.awt.Dimension(354, 303));

        jb_mode_jour.setBackground(new java.awt.Color(51, 51, 255));
        jb_mode_jour.setForeground(new java.awt.Color(255, 255, 0));
        jb_mode_jour.setText("Mode Jour");
        jb_mode_jour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_mode_jourActionPerformed(evt);
            }
        });

        jl_ttitre_nuit.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        jl_ttitre_nuit.setForeground(new java.awt.Color(255, 255, 0));
        jl_ttitre_nuit.setText("MODE NUIT :");

        jl_led.setBackground(new java.awt.Color(0, 0, 153));
        jl_led.setForeground(new java.awt.Color(255, 255, 255));
        jl_led.setOpaque(true);

        jb_intru.setText("intru");
        jb_intru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_intruActionPerformed(evt);
            }
        });

        jlp_nuit.setLayer(jb_mode_jour, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlp_nuit.setLayer(jl_ttitre_nuit, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlp_nuit.setLayer(jl_led, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlp_nuit.setLayer(jb_intru, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jlp_nuitLayout = new javax.swing.GroupLayout(jlp_nuit);
        jlp_nuit.setLayout(jlp_nuitLayout);
        jlp_nuitLayout.setHorizontalGroup(
            jlp_nuitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlp_nuitLayout.createSequentialGroup()
                .addContainerGap(113, Short.MAX_VALUE)
                .addGroup(jlp_nuitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jlp_nuitLayout.createSequentialGroup()
                        .addComponent(jl_ttitre_nuit, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(98, 98, 98))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jlp_nuitLayout.createSequentialGroup()
                        .addComponent(jb_intru)
                        .addGap(70, 70, 70)
                        .addComponent(jl_led, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jlp_nuitLayout.createSequentialGroup()
                        .addComponent(jb_mode_jour)
                        .addGap(132, 132, 132))))
        );
        jlp_nuitLayout.setVerticalGroup(
            jlp_nuitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlp_nuitLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jl_ttitre_nuit)
                .addGap(36, 36, 36)
                .addGroup(jlp_nuitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jl_led, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_intru))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(jb_mode_jour)
                .addGap(56, 56, 56))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlp_jour, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jlp_nuit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlp_jour)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jlp_nuit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void setIntrusion(Color c)
    {
        jl_led.setBackground(c);
    }
    
    public void setDate(String date)
    {
        jl_date.setText(date);
    }
    
    private void jb_mode_nuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_mode_nuitActionPerformed
        setMode(NUIT);
        //td.stop();
        
        jlp_jour.setOpaque(false);
        jlp_nuit.setOpaque(true);
        
        jlp_nuit.setVisible(true);
        jlp_jour.setVisible(false);
    }//GEN-LAST:event_jb_mode_nuitActionPerformed

    private void jb_mode_jourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_mode_jourActionPerformed
        setMode(JOUR);
        setJour(getJour()+1);
        //td.start();
        
        nbVisiteurs = 0;
        jl_nb_visiteurs.setText(Integer.toString(nbVisiteurs));
        
        ti.setActivation(false);
        setIntrusion(new Color(0,0,153));
        
        jlp_jour.setOpaque(true);
        jlp_nuit.setOpaque(false);
        
        jlp_nuit.setVisible(false);
        jlp_jour.setVisible(true);
    }//GEN-LAST:event_jb_mode_jourActionPerformed

    private void jb_intruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_intruActionPerformed
        ti.setActivation(true);
        ti.start();
    }//GEN-LAST:event_jb_intruActionPerformed

    private void jb_plusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_plusActionPerformed
        nbVisiteurs ++;
        jl_nb_visiteurs.setText(Integer.toString(nbVisiteurs));
    }//GEN-LAST:event_jb_plusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jb_intru;
    private javax.swing.JButton jb_mode_jour;
    private javax.swing.JButton jb_mode_nuit;
    private javax.swing.JButton jb_plus;
    private javax.swing.JLabel jl_date;
    private javax.swing.JLabel jl_intitule_visiteurs;
    private javax.swing.JLabel jl_led;
    private javax.swing.JLabel jl_nb_visiteurs;
    private javax.swing.JLabel jl_titre_jour;
    private javax.swing.JLabel jl_ttitre_nuit;
    private javax.swing.JLayeredPane jlp_jour;
    private javax.swing.JLayeredPane jlp_nuit;
    // End of variables declaration//GEN-END:variables
}
